// Generated by gencpp from file sbot_msg/Position2D.msg
// DO NOT EDIT!


#ifndef SBOT_MSG_MESSAGE_POSITION2D_H
#define SBOT_MSG_MESSAGE_POSITION2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sbot_msg
{
template <class ContainerAllocator>
struct Position2D_
{
  typedef Position2D_<ContainerAllocator> Type;

  Position2D_()
    : x(0.0)
    , y(0.0)  {
    }
  Position2D_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::sbot_msg::Position2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sbot_msg::Position2D_<ContainerAllocator> const> ConstPtr;

}; // struct Position2D_

typedef ::sbot_msg::Position2D_<std::allocator<void> > Position2D;

typedef boost::shared_ptr< ::sbot_msg::Position2D > Position2DPtr;
typedef boost::shared_ptr< ::sbot_msg::Position2D const> Position2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sbot_msg::Position2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sbot_msg::Position2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sbot_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sbot_msg': ['/home/felipe/sorterbot/src/sbot_msg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sbot_msg::Position2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sbot_msg::Position2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sbot_msg::Position2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sbot_msg::Position2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sbot_msg::Position2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sbot_msg::Position2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sbot_msg::Position2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::sbot_msg::Position2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::sbot_msg::Position2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sbot_msg/Position2D";
  }

  static const char* value(const ::sbot_msg::Position2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sbot_msg::Position2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#2D position of end effector\n\
\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::sbot_msg::Position2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sbot_msg::Position2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sbot_msg::Position2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sbot_msg::Position2D_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SBOT_MSG_MESSAGE_POSITION2D_H
